<a href="https://colab.research.google.com/github/soumak09/machineLearn/blob/main/one_hot_encoding_vs_label_encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [29]:
# creating initial dataframe
bridge_types = ('Arch','Beam','Truss','Cantilever','Tied Arch','Suspension','Cable')
bridge_df = pd.DataFrame(bridge_types, columns=['Bridge_Types'])

In [30]:
bridge_df

  Bridge_Types
0         Arch
1         Beam
2        Truss
3   Cantilever
4    Tied Arch
5   Suspension
6        Cable

In [31]:
# creating instance of labelencoder
labelencoder = LabelEncoder()

In [32]:
# Assigning numerical values and storing in another column
bridge_df['Bridge_Types_Cat'] = labelencoder.fit_transform(bridge_df['Bridge_Types'])
bridge_df

  Bridge_Types  Bridge_Types_Cat
0         Arch                 0
1         Beam                 1
2        Truss                 6
3   Cantilever                 3
4    Tied Arch                 5
5   Suspension                 4
6        Cable                 2

In [33]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder

In [34]:
# creating instance of one-hot-encoder
enc = OneHotEncoder(handle_unknown='ignore')

In [35]:
# passing bridge-types-cat column (label encoded values of bridge_types)
enc_df = pd.DataFrame(enc.fit_transform(bridge_df[['Bridge_Types_Cat']]).toarray())

In [36]:
enc_df

     0    1    2    3    4    5    6
0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0  0.0  0.0  1.0
3  0.0  0.0  0.0  1.0  0.0  0.0  0.0
4  0.0  0.0  0.0  0.0  0.0  1.0  0.0
5  0.0  0.0  0.0  0.0  1.0  0.0  0.0
6  0.0  0.0  1.0  0.0  0.0  0.0  0.0

In [37]:
# merge with main df bridge_df on key values
bridge_df = bridge_df.join(enc_df)
bridge_df

  Bridge_Types  Bridge_Types_Cat    0    1    2    3    4    5    6
0         Arch                 0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
1         Beam                 1  0.0  1.0  0.0  0.0  0.0  0.0  0.0
2        Truss                 6  0.0  0.0  0.0  0.0  0.0  0.0  1.0
3   Cantilever                 3  0.0  0.0  0.0  1.0  0.0  0.0  0.0
4    Tied Arch                 5  0.0  0.0  0.0  0.0  0.0  1.0  0.0
5   Suspension                 4  0.0  0.0  0.0  0.0  1.0  0.0  0.0
6        Cable                 2  0.0  0.0  1.0  0.0  0.0  0.0  0.0